"""Export Service — generates downloadable artifacts from blueprint data.

SDPD: Tier 0 (deterministic). Markdown and JSON are templated, not AI-generated.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any


def export_markdown(
    idea: str,
    blueprint: dict[str, Any],
    project_name: str = "My Project",
) -> str:
    """Generate a complete Markdown export from blueprint data.

    Args:
        idea: Original project idea.
        blueprint: Blueprint data from the coordinator.
        project_name: Name of the project.

    Returns:
        Complete Markdown string suitable for README.md or export.
    """
    lines: list[str] = []
    summary = blueprint.get("summary", {})
    stack = blueprint.get("tech_stack", {}) or {}
    arch = blueprint.get("architecture", {}) or {}
    dm = blueprint.get("data_model", {}) or {}
    api = blueprint.get("api_contracts", {}) or {}
    pl = blueprint.get("plan", {}) or {}

    # Title
    lines.append(f"# {project_name}")
    lines.append("")
    lines.append(f"> *Auto-generated by exHacker — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}*")
    lines.append("")

    # Overview
    lines.append("## 📋 Project Overview")
    lines.append("")
    lines.append(f"**Idea:** {idea}")
    lines.append("")
    if summary:
        lines.append(f"- Components: {summary.get('components', 0)}")
        lines.append(f"- Data entities: {summary.get('entities', 0)}")
        lines.append(f"- API endpoints: {summary.get('endpoints', 0)}")
        lines.append(f"- Implementation tasks: {summary.get('tasks', 0)}")
        lines.append(f"- Estimated effort: {summary.get('estimated_hours', 0)} hours")
    lines.append("")

    # Tech Stack
    lines.append("## 🛠️ Tech Stack")
    lines.append("")
    frontend = stack.get("frontend", {}) or {}
    backend = stack.get("backend", {}) or {}
    database = stack.get("database", {}) or {}
    ai_prov = stack.get("ai", {}) or {}
    auth = stack.get("auth", {}) or {}
    hosting = stack.get("hosting", {}) or {}

    if frontend:
        lines.append(f"- **Frontend:** {frontend.get('framework', 'N/A')}")
    if backend:
        lines.append(f"- **Backend:** {backend.get('framework', 'N/A')}")
    if database:
        lines.append(f"- **Database:** {database.get('database', 'N/A')}")
    if ai_prov:
        lines.append(f"- **AI:** {ai_prov.get('provider', 'None')}")
    if auth:
        lines.append(f"- **Auth:** {auth.get('provider', 'None')}")
    if hosting:
        lines.append(f"- **Hosting:** {hosting.get('platform', 'N/A')}")
    lines.append("")

    # Explanations
    explanations = stack.get("explanations", {}) or {}
    if explanations:
        lines.append("### Why This Stack?")
        lines.append("")
        for key, explanation in explanations.items():
            if isinstance(explanation, str) and explanation.strip():
                lines.append(f"- **{key.capitalize()}:** {explanation}")
        lines.append("")

    # Architecture
    components = (arch.get("components") or []) if arch else []
    if components:
        lines.append("## 🏗️ Architecture")
        lines.append("")
        for comp in components:
            name = comp.get("name", "Component")
            desc = comp.get("description", "")
            tech = comp.get("tech", "")
            lines.append(f"### {name}")
            if desc:
                lines.append(f"*{desc}*")
            lines.append("")
            if tech:
                lines.append(f"- **Tech:** {tech}")
            resp = comp.get("responsibilities", [])
            if resp:
                lines.append("- **Responsibilities:**")
                for r in resp:
                    lines.append(f"  - {r}")
            sub = comp.get("sub_components", [])
            if sub:
                lines.append("- **Sub-components:**")
                for s in sub:
                    lines.append(f"  - {s}")
            lines.append("")

    # Data Model
    entities = (dm.get("entities") or []) if dm else []
    if entities:
        lines.append("## 📊 Data Model")
        lines.append("")
        for entity in entities:
            name = entity.get("name", "Entity")
            lines.append(f"### {name.capitalize()}")
            lines.append("")
            fields = entity.get("fields", [])
            if fields:
                lines.append("| Field | Type | Description |")
                lines.append("|-------|------|-------------|")
                for f in fields:
                    fname = f.get("name", "")
                    ftype = f.get("type", "")
                    fdesc = f.get("description", "")
                    lines.append(f"| {fname} | `{ftype}` | {fdesc} |")
            lines.append("")

    # Relationships
    relationships = (dm.get("relationships") or []) if dm else []
    if relationships:
        lines.append("### Relationships")
        lines.append("")
        lines.append("| From | To | Type | Description |")
        lines.append("|------|-----|------|-------------|")
        for rel in relationships:
            lines.append(
                f"| {rel.get('from', '')} | {rel.get('to', '')} | "
                f"{rel.get('type', '')} | {rel.get('description', '')} |"
            )
        lines.append("")

    # API Contracts
    endpoints = (api.get("endpoints") or []) if api else []
    if endpoints:
        lines.append("## 🔌 API Endpoints")
        lines.append("")
        lines.append(f"**Base URL:** `{api.get('base_url', '/api/v1')}`")
        lines.append(f"**Auth:** {api.get('auth', 'Bearer JWT')}")
        lines.append("")
        lines.append("| Method | Path | Description | Auth |")
        lines.append("|--------|------|-------------|------|")
        for ep in endpoints:
            lines.append(
                f"| {ep.get('method', 'GET')} | `{ep.get('path', '/')}` | "
                f"{ep.get('description', '')} | {ep.get('auth', 'Required')} |"
            )
        lines.append("")

    # Plan
    phases = (pl.get("phases") or []) if pl else []
    if phases:
        lines.append("## 📋 Implementation Plan")
        lines.append("")
        lines.append(f"**Total:** {pl.get('total_tasks', 0)} tasks, ~{pl.get('estimated_hours', 0)} hours")
        lines.append("")
        for i, phase in enumerate(phases):
            pname = phase.get("name", f"Phase {i + 1}")
            lines.append(f"### Phase {i + 1}: {pname}")
            lines.append("")
            tasks = phase.get("tasks", [])
            for t in tasks:
                title = t.get("title", "")
                hours = t.get("estimated_hours", 0)
                lines.append(f"- [ ] {title} ({hours}h)")
            lines.append("")

    # Footer
    lines.append("---")
    lines.append(
        f"*Generated by exHacker on {datetime.now(timezone.utc).strftime('%Y-%m-%d at %H:%M UTC')}*"
    )

    return "\n".join(lines)


def export_json(blueprint: dict[str, Any]) -> str:
    """Serialize blueprint data as formatted JSON.

    Args:
        blueprint: Blueprint data from the coordinator.

    Returns:
        Pretty-printed JSON string.
    """
    return json.dumps(blueprint, indent=2, default=str)


def get_export_filename(project_name: str, fmt: str = "md") -> str:
    """Generate a safe filename for the export."""
    safe_name = "".join(c if c.isalnum() or c in " -_" else "_" for c in project_name)
    safe_name = safe_name.strip().replace(" ", "-").lower()[:50]
    return f"{safe_name}-blueprint.{fmt}"
