"""add thread_id to projects

Revision ID: 4b89f89f1099
Revises: b1c2d3e4f5a6
Create Date: 2026-06-09 22:55:55.409532
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b89f89f1099'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('thread_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'thread_id')
    # ### end Alembic commands ###
