"""add idea_selection and failed statuses, thread_id

Revision ID: fa53a03ab3ce
Revises: 4b89f89f1099
Create Date: 2026-06-09 22:57:43.977533
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fa53a03ab3ce'
down_revision: Union[str, None] = '4b89f89f1099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
